# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-25 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_homeshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeshow',
            name='longname1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='homeshow',
            name='longname2',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='homeshow',
            name='longname3',
            field=models.CharField(max_length=40),
        ),
    ]
